DELETE FROM TAGS WHERE TAGS.PAGEID IN (SELECT PAGES.ID FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/mentions%');
DELETE FROM MENTIONS WHERE MENTIONS.PAGEID IN (SELECT PAGES.ID FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/mentions%');
DELETE FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/mentions%';

DELETE FROM TAGS WHERE TAGS.PAGEID IN (SELECT PAGES.ID FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/hashtags%');
DELETE FROM MENTIONS WHERE MENTIONS.PAGEID IN (SELECT PAGES.ID FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/hashtags%');
DELETE FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/hashtags%';

DELETE FROM TAGS WHERE TAGS.PAGEID IN (SELECT PAGES.ID FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/image-search%');
DELETE FROM MENTIONS WHERE MENTIONS.PAGEID IN (SELECT PAGES.ID FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/image-search%');
DELETE FROM PAGES WHERE PAGES.URL LIKE 'gemini://kennedy.gemi.dev/image-search%';