package migrations

import (
	"context"
	"database/sql"
	"time"

	"gitlab.com/clseibold/auragem_sis/db"
	"gitlab.com/clseibold/auragem_sis/migration/types"
)

func init() {
	registerMigration(SearchAudioTranscripts{})
}

type SearchAudioTranscripts struct{}

func (m SearchAudioTranscripts) Version() types.MigrationVersion {
	return types.MigrationVersion(time.Date(2022, 7, 21, 5, 44, 19, 0, time.UTC))
}

func (m SearchAudioTranscripts) Name() string {
	return "SearchAudioTranscripts"
}

func (m SearchAudioTranscripts) DB() db.DBType {
	return db.SearchDB
}

func (m SearchAudioTranscripts) Description() string {
	return "AudioTranscripts table for Search database"
}

func (m SearchAudioTranscripts) Up(tx *sql.Tx) error {
	_, err := tx.ExecContext(context.Background(), `
	CREATE TABLE audiotranscripts (
		id bigint generated by default as identity primary key,
		pageid bigint references pages,
		text BLOB SUB_TYPE TEXT CHARACTER SET UTF8 COLLATE UNICODE_CI,
		date_added timestamp with time zone NOT NULL
	);
	`)
	if err != nil {
		return err
	}

	return nil
}

func (m SearchAudioTranscripts) Down(tx *sql.Tx) error {
	panic("Implement me")
}
