package migrations

import (
	"context"
	"database/sql"
	"time"

	"gitlab.com/clseibold/auragem_sis/db"
	"gitlab.com/clseibold/auragem_sis/migration/types"
)

func init() {
	registerMigration(SearchSeedsTable{})
}

type SearchSeedsTable struct{}

func (m SearchSeedsTable) Version() types.MigrationVersion {
	return types.MigrationVersion(time.Date(2022, 8, 7, 8, 45, 53, 0, time.UTC))
}

func (m SearchSeedsTable) Name() string {
	return "SearchSeedsTable"
}

func (m SearchSeedsTable) DB() db.DBType {
	return db.SearchDB
}

func (m SearchSeedsTable) Description() string {
	return "Search Engine Seeds table to seed the crawler"
}

func (m SearchSeedsTable) Up(tx *sql.Tx) error {
	_, err := tx.ExecContext(context.Background(), `
	CREATE TABLE seeds (
		id bigint generated by default as identity primary key,
		url character varying(1020) NOT NULL COLLATE UNICODE_CI,
		date_added timestamp with time zone NOT NULL
	);
	`)
	if err != nil {
		return err
	}

	return nil
}

func (m SearchSeedsTable) Down(tx *sql.Tx) error {
	panic("Implement me")
}
