package migrations

import (
	"context"
	"database/sql"
	"time"

	"gitlab.com/clseibold/auragem_sis/db"
	"gitlab.com/clseibold/auragem_sis/migration/types"
)

func init() {
	registerMigration(SearchMentionsTable{})
}

type SearchMentionsTable struct{}

func (m SearchMentionsTable) Version() types.MigrationVersion {
	return types.MigrationVersion(time.Date(2022, 7, 19, 0, 24, 37, 0, time.UTC))
}

func (m SearchMentionsTable) Name() string {
	return "SearchMentionsTable"
}

func (m SearchMentionsTable) DB() db.DBType {
	return db.SearchDB
}

func (m SearchMentionsTable) Description() string {
	return "Mentions table for search engine"
}

func (m SearchMentionsTable) Up(tx *sql.Tx) error {
	_, err := tx.ExecContext(context.Background(), `
	CREATE TABLE mentions (
		id bigint generated by default as identity primary key,
		pageid bigint references pages,
		name character varying(250) NOT NULL COLLATE UNICODE_CI,
		crawlIndex integer,
		date_added timestamp with time zone NOT NULL
	);
	`)
	if err != nil {
		return err
	}

	return nil
}

func (m SearchMentionsTable) Down(tx *sql.Tx) error {
	panic("Implement me")
}
